/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "power_profiles_dbus.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

#ifdef G_ENABLE_DEBUG
#define g_marshal_value_peek_boolean(v)  g_value_get_boolean (v)
#define g_marshal_value_peek_char(v)     g_value_get_schar (v)
#define g_marshal_value_peek_uchar(v)    g_value_get_uchar (v)
#define g_marshal_value_peek_int(v)      g_value_get_int (v)
#define g_marshal_value_peek_uint(v)     g_value_get_uint (v)
#define g_marshal_value_peek_long(v)     g_value_get_long (v)
#define g_marshal_value_peek_ulong(v)    g_value_get_ulong (v)
#define g_marshal_value_peek_int64(v)    g_value_get_int64 (v)
#define g_marshal_value_peek_uint64(v)   g_value_get_uint64 (v)
#define g_marshal_value_peek_enum(v)     g_value_get_enum (v)
#define g_marshal_value_peek_flags(v)    g_value_get_flags (v)
#define g_marshal_value_peek_float(v)    g_value_get_float (v)
#define g_marshal_value_peek_double(v)   g_value_get_double (v)
#define g_marshal_value_peek_string(v)   (char*) g_value_get_string (v)
#define g_marshal_value_peek_param(v)    g_value_get_param (v)
#define g_marshal_value_peek_boxed(v)    g_value_get_boxed (v)
#define g_marshal_value_peek_pointer(v)  g_value_get_pointer (v)
#define g_marshal_value_peek_object(v)   g_value_get_object (v)
#define g_marshal_value_peek_variant(v)  g_value_get_variant (v)
#else /* !G_ENABLE_DEBUG */
/* WARNING: This code accesses GValues directly, which is UNSUPPORTED API.
 *          Do not access GValues directly in your code. Instead, use the
 *          g_value_get_*() functions
 */
#define g_marshal_value_peek_boolean(v)  (v)->data[0].v_int
#define g_marshal_value_peek_char(v)     (v)->data[0].v_int
#define g_marshal_value_peek_uchar(v)    (v)->data[0].v_uint
#define g_marshal_value_peek_int(v)      (v)->data[0].v_int
#define g_marshal_value_peek_uint(v)     (v)->data[0].v_uint
#define g_marshal_value_peek_long(v)     (v)->data[0].v_long
#define g_marshal_value_peek_ulong(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_int64(v)    (v)->data[0].v_int64
#define g_marshal_value_peek_uint64(v)   (v)->data[0].v_uint64
#define g_marshal_value_peek_enum(v)     (v)->data[0].v_long
#define g_marshal_value_peek_flags(v)    (v)->data[0].v_ulong
#define g_marshal_value_peek_float(v)    (v)->data[0].v_float
#define g_marshal_value_peek_double(v)   (v)->data[0].v_double
#define g_marshal_value_peek_string(v)   (v)->data[0].v_pointer
#define g_marshal_value_peek_param(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_boxed(v)    (v)->data[0].v_pointer
#define g_marshal_value_peek_pointer(v)  (v)->data[0].v_pointer
#define g_marshal_value_peek_object(v)   (v)->data[0].v_pointer
#define g_marshal_value_peek_variant(v)  (v)->data[0].v_pointer
#endif /* !G_ENABLE_DEBUG */

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  guint use_gvariant : 1;
  guint emits_changed_signal : 1;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

static void
_g_dbus_codegen_marshal_BOOLEAN__OBJECT_STRING_STRING_STRING (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint G_GNUC_UNUSED,
    void         *marshal_data)
{
  typedef gboolean (*_GDbusCodegenMarshalBoolean_ObjectStringStringStringFunc)
       (void *data1,
        GDBusMethodInvocation *arg_method_invocation,
        const gchar *arg_profile,
        const gchar *arg_reason,
        const gchar *arg_application_id,
        void *data2);
  _GDbusCodegenMarshalBoolean_ObjectStringStringStringFunc callback;
  GCClosure *cc = (GCClosure*) closure;
  void *data1, *data2;
  gboolean v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 5);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = g_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = g_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }

  callback = (_GDbusCodegenMarshalBoolean_ObjectStringStringStringFunc)
    (marshal_data ? marshal_data : cc->callback);

  v_return =
    callback (data1,
              g_marshal_value_peek_object (param_values + 1),
              g_marshal_value_peek_string (param_values + 2),
              g_marshal_value_peek_string (param_values + 3),
              g_marshal_value_peek_string (param_values + 4),
              data2);

  g_value_set_boolean (return_value, v_return);
}

static void
_g_dbus_codegen_marshal_BOOLEAN__OBJECT_UINT (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint G_GNUC_UNUSED,
    void         *marshal_data)
{
  typedef gboolean (*_GDbusCodegenMarshalBoolean_ObjectUintFunc)
       (void *data1,
        GDBusMethodInvocation *arg_method_invocation,
        guint arg_cookie,
        void *data2);
  _GDbusCodegenMarshalBoolean_ObjectUintFunc callback;
  GCClosure *cc = (GCClosure*) closure;
  void *data1, *data2;
  gboolean v_return;

  g_return_if_fail (return_value != NULL);
  g_return_if_fail (n_param_values == 3);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      data1 = closure->data;
      data2 = g_value_peek_pointer (param_values + 0);
    }
  else
    {
      data1 = g_value_peek_pointer (param_values + 0);
      data2 = closure->data;
    }

  callback = (_GDbusCodegenMarshalBoolean_ObjectUintFunc)
    (marshal_data ? marshal_data : cc->callback);

  v_return =
    callback (data1,
              g_marshal_value_peek_object (param_values + 1),
              g_marshal_value_peek_uint (param_values + 2),
              data2);

  g_value_set_boolean (return_value, v_return);
}

/* ------------------------------------------------------------------------
 * Code for interface net.hadess.PowerProfiles
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:DbusPowerProfiles
 * @title: DbusPowerProfiles
 * @short_description: Generated C code for the net.hadess.PowerProfiles D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-net-hadess-PowerProfiles.top_of_page">net.hadess.PowerProfiles</link> D-Bus interface in C.
 */

enum
{
  DBUS__POWER_PROFILES_PROFILE_RELEASED,
};

static unsigned DBUS__POWER_PROFILES_SIGNALS[1] = { 0 };

/* ---- Introspection data for net.hadess.PowerProfiles ---- */

static const _ExtendedGDBusArgInfo _dbus_power_profiles_method_info_hold_profile_IN_ARG_profile =
{
  {
    -1,
    (gchar *) "profile",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _dbus_power_profiles_method_info_hold_profile_IN_ARG_reason =
{
  {
    -1,
    (gchar *) "reason",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _dbus_power_profiles_method_info_hold_profile_IN_ARG_application_id =
{
  {
    -1,
    (gchar *) "application_id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _dbus_power_profiles_method_info_hold_profile_IN_ARG_pointers[] =
{
  &_dbus_power_profiles_method_info_hold_profile_IN_ARG_profile.parent_struct,
  &_dbus_power_profiles_method_info_hold_profile_IN_ARG_reason.parent_struct,
  &_dbus_power_profiles_method_info_hold_profile_IN_ARG_application_id.parent_struct,
  NULL
};

static const _ExtendedGDBusArgInfo _dbus_power_profiles_method_info_hold_profile_OUT_ARG_cookie =
{
  {
    -1,
    (gchar *) "cookie",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _dbus_power_profiles_method_info_hold_profile_OUT_ARG_pointers[] =
{
  &_dbus_power_profiles_method_info_hold_profile_OUT_ARG_cookie.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _dbus_power_profiles_method_info_hold_profile =
{
  {
    -1,
    (gchar *) "HoldProfile",
    (GDBusArgInfo **) &_dbus_power_profiles_method_info_hold_profile_IN_ARG_pointers,
    (GDBusArgInfo **) &_dbus_power_profiles_method_info_hold_profile_OUT_ARG_pointers,
    NULL
  },
  "handle-hold-profile",
  FALSE
};

static const _ExtendedGDBusArgInfo _dbus_power_profiles_method_info_release_profile_IN_ARG_cookie =
{
  {
    -1,
    (gchar *) "cookie",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _dbus_power_profiles_method_info_release_profile_IN_ARG_pointers[] =
{
  &_dbus_power_profiles_method_info_release_profile_IN_ARG_cookie.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _dbus_power_profiles_method_info_release_profile =
{
  {
    -1,
    (gchar *) "ReleaseProfile",
    (GDBusArgInfo **) &_dbus_power_profiles_method_info_release_profile_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-release-profile",
  FALSE
};

static const GDBusMethodInfo * const _dbus_power_profiles_method_info_pointers[] =
{
  &_dbus_power_profiles_method_info_hold_profile.parent_struct,
  &_dbus_power_profiles_method_info_release_profile.parent_struct,
  NULL
};

static const _ExtendedGDBusArgInfo _dbus_power_profiles_signal_info_profile_released_ARG_cookie =
{
  {
    -1,
    (gchar *) "cookie",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _dbus_power_profiles_signal_info_profile_released_ARG_pointers[] =
{
  &_dbus_power_profiles_signal_info_profile_released_ARG_cookie.parent_struct,
  NULL
};

static const _ExtendedGDBusSignalInfo _dbus_power_profiles_signal_info_profile_released =
{
  {
    -1,
    (gchar *) "ProfileReleased",
    (GDBusArgInfo **) &_dbus_power_profiles_signal_info_profile_released_ARG_pointers,
    NULL
  },
  "profile-released"
};

static const GDBusSignalInfo * const _dbus_power_profiles_signal_info_pointers[] =
{
  &_dbus_power_profiles_signal_info_profile_released.parent_struct,
  NULL
};

static const _ExtendedGDBusPropertyInfo _dbus_power_profiles_property_info_active_profile =
{
  {
    -1,
    (gchar *) "ActiveProfile",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "active-profile",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _dbus_power_profiles_property_info_performance_inhibited =
{
  {
    -1,
    (gchar *) "PerformanceInhibited",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "performance-inhibited",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _dbus_power_profiles_property_info_performance_degraded =
{
  {
    -1,
    (gchar *) "PerformanceDegraded",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "performance-degraded",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _dbus_power_profiles_property_info_profiles =
{
  {
    -1,
    (gchar *) "Profiles",
    (gchar *) "aa{sv}",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "profiles",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _dbus_power_profiles_property_info_actions =
{
  {
    -1,
    (gchar *) "Actions",
    (gchar *) "as",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "actions",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _dbus_power_profiles_property_info_active_profile_holds =
{
  {
    -1,
    (gchar *) "ActiveProfileHolds",
    (gchar *) "aa{sv}",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "active-profile-holds",
  FALSE,
  TRUE
};

static const GDBusPropertyInfo * const _dbus_power_profiles_property_info_pointers[] =
{
  &_dbus_power_profiles_property_info_active_profile.parent_struct,
  &_dbus_power_profiles_property_info_performance_inhibited.parent_struct,
  &_dbus_power_profiles_property_info_performance_degraded.parent_struct,
  &_dbus_power_profiles_property_info_profiles.parent_struct,
  &_dbus_power_profiles_property_info_actions.parent_struct,
  &_dbus_power_profiles_property_info_active_profile_holds.parent_struct,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _dbus_power_profiles_interface_info =
{
  {
    -1,
    (gchar *) "net.hadess.PowerProfiles",
    (GDBusMethodInfo **) &_dbus_power_profiles_method_info_pointers,
    (GDBusSignalInfo **) &_dbus_power_profiles_signal_info_pointers,
    (GDBusPropertyInfo **) &_dbus_power_profiles_property_info_pointers,
    NULL
  },
  "power-profiles",
};


/**
 * dbus_power_profiles_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-net-hadess-PowerProfiles.top_of_page">net.hadess.PowerProfiles</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
dbus_power_profiles_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_dbus_power_profiles_interface_info.parent_struct;
}

/**
 * dbus_power_profiles_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #DbusPowerProfiles interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
dbus_power_profiles_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "active-profile");
  g_object_class_override_property (klass, property_id_begin++, "performance-inhibited");
  g_object_class_override_property (klass, property_id_begin++, "performance-degraded");
  g_object_class_override_property (klass, property_id_begin++, "profiles");
  g_object_class_override_property (klass, property_id_begin++, "actions");
  g_object_class_override_property (klass, property_id_begin++, "active-profile-holds");
  return property_id_begin - 1;
}


inline static void
dbus_power_profiles_signal_marshal_profile_released (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint,
    void         *marshal_data)
{
  g_cclosure_marshal_VOID__UINT (closure,
    return_value, n_param_values, param_values, invocation_hint, marshal_data);
}

inline static void
dbus_power_profiles_method_marshal_hold_profile (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint,
    void         *marshal_data)
{
  _g_dbus_codegen_marshal_BOOLEAN__OBJECT_STRING_STRING_STRING (closure,
    return_value, n_param_values, param_values, invocation_hint, marshal_data);
}

inline static void
dbus_power_profiles_method_marshal_release_profile (
    GClosure     *closure,
    GValue       *return_value,
    unsigned int  n_param_values,
    const GValue *param_values,
    void         *invocation_hint,
    void         *marshal_data)
{
  _g_dbus_codegen_marshal_BOOLEAN__OBJECT_UINT (closure,
    return_value, n_param_values, param_values, invocation_hint, marshal_data);
}


/**
 * DbusPowerProfiles:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-net-hadess-PowerProfiles.top_of_page">net.hadess.PowerProfiles</link>.
 */

/**
 * DbusPowerProfilesIface:
 * @parent_iface: The parent interface.
 * @handle_hold_profile: Handler for the #DbusPowerProfiles::handle-hold-profile signal.
 * @handle_release_profile: Handler for the #DbusPowerProfiles::handle-release-profile signal.
 * @get_actions: Getter for the #DbusPowerProfiles:actions property.
 * @get_active_profile: Getter for the #DbusPowerProfiles:active-profile property.
 * @get_active_profile_holds: Getter for the #DbusPowerProfiles:active-profile-holds property.
 * @get_performance_degraded: Getter for the #DbusPowerProfiles:performance-degraded property.
 * @get_performance_inhibited: Getter for the #DbusPowerProfiles:performance-inhibited property.
 * @get_profiles: Getter for the #DbusPowerProfiles:profiles property.
 * @profile_released: Handler for the #DbusPowerProfiles::profile-released signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-net-hadess-PowerProfiles.top_of_page">net.hadess.PowerProfiles</link>.
 */

typedef DbusPowerProfilesIface DbusPowerProfilesInterface;
G_DEFINE_INTERFACE (DbusPowerProfiles, dbus_power_profiles, G_TYPE_OBJECT)

static void
dbus_power_profiles_default_init (DbusPowerProfilesIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * DbusPowerProfiles::handle-hold-profile:
   * @object: A #DbusPowerProfiles.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_profile: Argument passed by remote caller.
   * @arg_reason: Argument passed by remote caller.
   * @arg_application_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-net-hadess-PowerProfiles.HoldProfile">HoldProfile()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call dbus_power_profiles_complete_hold_profile() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-hold-profile",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (DbusPowerProfilesIface, handle_hold_profile),
    g_signal_accumulator_true_handled,
    NULL,
      dbus_power_profiles_method_marshal_hold_profile,
    G_TYPE_BOOLEAN,
    4,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);

  /**
   * DbusPowerProfiles::handle-release-profile:
   * @object: A #DbusPowerProfiles.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_cookie: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-net-hadess-PowerProfiles.ReleaseProfile">ReleaseProfile()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call dbus_power_profiles_complete_release_profile() or e.g. g_dbus_method_invocation_return_error() on it) and no other signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %G_DBUS_METHOD_INVOCATION_HANDLED or %TRUE if the invocation was handled, %G_DBUS_METHOD_INVOCATION_UNHANDLED or %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-release-profile",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (DbusPowerProfilesIface, handle_release_profile),
    g_signal_accumulator_true_handled,
    NULL,
      dbus_power_profiles_method_marshal_release_profile,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT);

  /* GObject signals for received D-Bus signals: */
  /**
   * DbusPowerProfiles::profile-released:
   * @object: A #DbusPowerProfiles.
   * @arg_cookie: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-net-hadess-PowerProfiles.ProfileReleased">"ProfileReleased"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  DBUS__POWER_PROFILES_SIGNALS[DBUS__POWER_PROFILES_PROFILE_RELEASED] =
    g_signal_new ("profile-released",
      G_TYPE_FROM_INTERFACE (iface),
      G_SIGNAL_RUN_LAST,
      G_STRUCT_OFFSET (DbusPowerProfilesIface, profile_released),
      NULL,
      NULL,
      dbus_power_profiles_signal_marshal_profile_released,
      G_TYPE_NONE,
      1, G_TYPE_UINT);

  /* GObject properties for D-Bus properties: */
  /**
   * DbusPowerProfiles:active-profile:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-net-hadess-PowerProfiles.ActiveProfile">"ActiveProfile"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("active-profile", "ActiveProfile", "ActiveProfile", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * DbusPowerProfiles:performance-inhibited:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-net-hadess-PowerProfiles.PerformanceInhibited">"PerformanceInhibited"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("performance-inhibited", "PerformanceInhibited", "PerformanceInhibited", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * DbusPowerProfiles:performance-degraded:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-net-hadess-PowerProfiles.PerformanceDegraded">"PerformanceDegraded"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("performance-degraded", "PerformanceDegraded", "PerformanceDegraded", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * DbusPowerProfiles:profiles:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-net-hadess-PowerProfiles.Profiles">"Profiles"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_variant ("profiles", "Profiles", "Profiles", G_VARIANT_TYPE ("aa{sv}"), NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * DbusPowerProfiles:actions:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-net-hadess-PowerProfiles.Actions">"Actions"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boxed ("actions", "Actions", "Actions", G_TYPE_STRV, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * DbusPowerProfiles:active-profile-holds:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-net-hadess-PowerProfiles.ActiveProfileHolds">"ActiveProfileHolds"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_variant ("active-profile-holds", "ActiveProfileHolds", "ActiveProfileHolds", G_VARIANT_TYPE ("aa{sv}"), NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * dbus_power_profiles_get_active_profile: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets the value of the <link linkend="gdbus-property-net-hadess-PowerProfiles.ActiveProfile">"ActiveProfile"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use dbus_power_profiles_dup_active_profile() if on another thread.
 *
 * Returns: (transfer none) (nullable): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
dbus_power_profiles_get_active_profile (DbusPowerProfiles *object)
{
  g_return_val_if_fail (DBUS_IS_POWER_PROFILES (object), NULL);

  return DBUS_POWER_PROFILES_GET_IFACE (object)->get_active_profile (object);
}

/**
 * dbus_power_profiles_dup_active_profile: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets a copy of the <link linkend="gdbus-property-net-hadess-PowerProfiles.ActiveProfile">"ActiveProfile"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full) (nullable): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
dbus_power_profiles_dup_active_profile (DbusPowerProfiles *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "active-profile", &value, NULL);
  return value;
}

/**
 * dbus_power_profiles_set_active_profile: (skip)
 * @object: A #DbusPowerProfiles.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-net-hadess-PowerProfiles.ActiveProfile">"ActiveProfile"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
dbus_power_profiles_set_active_profile (DbusPowerProfiles *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "active-profile", value, NULL);
}

/**
 * dbus_power_profiles_get_performance_inhibited: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets the value of the <link linkend="gdbus-property-net-hadess-PowerProfiles.PerformanceInhibited">"PerformanceInhibited"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use dbus_power_profiles_dup_performance_inhibited() if on another thread.
 *
 * Returns: (transfer none) (nullable): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
dbus_power_profiles_get_performance_inhibited (DbusPowerProfiles *object)
{
  g_return_val_if_fail (DBUS_IS_POWER_PROFILES (object), NULL);

  return DBUS_POWER_PROFILES_GET_IFACE (object)->get_performance_inhibited (object);
}

/**
 * dbus_power_profiles_dup_performance_inhibited: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets a copy of the <link linkend="gdbus-property-net-hadess-PowerProfiles.PerformanceInhibited">"PerformanceInhibited"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full) (nullable): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
dbus_power_profiles_dup_performance_inhibited (DbusPowerProfiles *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "performance-inhibited", &value, NULL);
  return value;
}

/**
 * dbus_power_profiles_set_performance_inhibited: (skip)
 * @object: A #DbusPowerProfiles.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-net-hadess-PowerProfiles.PerformanceInhibited">"PerformanceInhibited"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
dbus_power_profiles_set_performance_inhibited (DbusPowerProfiles *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "performance-inhibited", value, NULL);
}

/**
 * dbus_power_profiles_get_performance_degraded: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets the value of the <link linkend="gdbus-property-net-hadess-PowerProfiles.PerformanceDegraded">"PerformanceDegraded"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use dbus_power_profiles_dup_performance_degraded() if on another thread.
 *
 * Returns: (transfer none) (nullable): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
dbus_power_profiles_get_performance_degraded (DbusPowerProfiles *object)
{
  g_return_val_if_fail (DBUS_IS_POWER_PROFILES (object), NULL);

  return DBUS_POWER_PROFILES_GET_IFACE (object)->get_performance_degraded (object);
}

/**
 * dbus_power_profiles_dup_performance_degraded: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets a copy of the <link linkend="gdbus-property-net-hadess-PowerProfiles.PerformanceDegraded">"PerformanceDegraded"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full) (nullable): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
dbus_power_profiles_dup_performance_degraded (DbusPowerProfiles *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "performance-degraded", &value, NULL);
  return value;
}

/**
 * dbus_power_profiles_set_performance_degraded: (skip)
 * @object: A #DbusPowerProfiles.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-net-hadess-PowerProfiles.PerformanceDegraded">"PerformanceDegraded"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
dbus_power_profiles_set_performance_degraded (DbusPowerProfiles *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "performance-degraded", value, NULL);
}

/**
 * dbus_power_profiles_get_profiles: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets the value of the <link linkend="gdbus-property-net-hadess-PowerProfiles.Profiles">"Profiles"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use dbus_power_profiles_dup_profiles() if on another thread.
 *
 * Returns: (transfer none) (nullable): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
GVariant *
dbus_power_profiles_get_profiles (DbusPowerProfiles *object)
{
  g_return_val_if_fail (DBUS_IS_POWER_PROFILES (object), NULL);

  return DBUS_POWER_PROFILES_GET_IFACE (object)->get_profiles (object);
}

/**
 * dbus_power_profiles_dup_profiles: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets a copy of the <link linkend="gdbus-property-net-hadess-PowerProfiles.Profiles">"Profiles"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full) (nullable): The property value or %NULL if the property is not set. The returned value should be freed with g_variant_unref().
 */
GVariant *
dbus_power_profiles_dup_profiles (DbusPowerProfiles *object)
{
  GVariant *value;
  g_object_get (G_OBJECT (object), "profiles", &value, NULL);
  return value;
}

/**
 * dbus_power_profiles_set_profiles: (skip)
 * @object: A #DbusPowerProfiles.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-net-hadess-PowerProfiles.Profiles">"Profiles"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
dbus_power_profiles_set_profiles (DbusPowerProfiles *object, GVariant *value)
{
  g_object_set (G_OBJECT (object), "profiles", value, NULL);
}

/**
 * dbus_power_profiles_get_actions: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets the value of the <link linkend="gdbus-property-net-hadess-PowerProfiles.Actions">"Actions"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use dbus_power_profiles_dup_actions() if on another thread.
 *
 * Returns: (transfer none) (nullable): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *const *
dbus_power_profiles_get_actions (DbusPowerProfiles *object)
{
  g_return_val_if_fail (DBUS_IS_POWER_PROFILES (object), NULL);

  return DBUS_POWER_PROFILES_GET_IFACE (object)->get_actions (object);
}

/**
 * dbus_power_profiles_dup_actions: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets a copy of the <link linkend="gdbus-property-net-hadess-PowerProfiles.Actions">"Actions"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full) (nullable): The property value or %NULL if the property is not set. The returned value should be freed with g_strfreev().
 */
gchar **
dbus_power_profiles_dup_actions (DbusPowerProfiles *object)
{
  gchar **value;
  g_object_get (G_OBJECT (object), "actions", &value, NULL);
  return value;
}

/**
 * dbus_power_profiles_set_actions: (skip)
 * @object: A #DbusPowerProfiles.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-net-hadess-PowerProfiles.Actions">"Actions"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
dbus_power_profiles_set_actions (DbusPowerProfiles *object, const gchar *const *value)
{
  g_object_set (G_OBJECT (object), "actions", value, NULL);
}

/**
 * dbus_power_profiles_get_active_profile_holds: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets the value of the <link linkend="gdbus-property-net-hadess-PowerProfiles.ActiveProfileHolds">"ActiveProfileHolds"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use dbus_power_profiles_dup_active_profile_holds() if on another thread.
 *
 * Returns: (transfer none) (nullable): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
GVariant *
dbus_power_profiles_get_active_profile_holds (DbusPowerProfiles *object)
{
  g_return_val_if_fail (DBUS_IS_POWER_PROFILES (object), NULL);

  return DBUS_POWER_PROFILES_GET_IFACE (object)->get_active_profile_holds (object);
}

/**
 * dbus_power_profiles_dup_active_profile_holds: (skip)
 * @object: A #DbusPowerProfiles.
 *
 * Gets a copy of the <link linkend="gdbus-property-net-hadess-PowerProfiles.ActiveProfileHolds">"ActiveProfileHolds"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full) (nullable): The property value or %NULL if the property is not set. The returned value should be freed with g_variant_unref().
 */
GVariant *
dbus_power_profiles_dup_active_profile_holds (DbusPowerProfiles *object)
{
  GVariant *value;
  g_object_get (G_OBJECT (object), "active-profile-holds", &value, NULL);
  return value;
}

/**
 * dbus_power_profiles_set_active_profile_holds: (skip)
 * @object: A #DbusPowerProfiles.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-net-hadess-PowerProfiles.ActiveProfileHolds">"ActiveProfileHolds"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
dbus_power_profiles_set_active_profile_holds (DbusPowerProfiles *object, GVariant *value)
{
  g_object_set (G_OBJECT (object), "active-profile-holds", value, NULL);
}

/**
 * dbus_power_profiles_emit_profile_released:
 * @object: A #DbusPowerProfiles.
 * @arg_cookie: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-net-hadess-PowerProfiles.ProfileReleased">"ProfileReleased"</link> D-Bus signal.
 */
void
dbus_power_profiles_emit_profile_released (
    DbusPowerProfiles *object,
    guint arg_cookie)
{
  g_signal_emit (object, DBUS__POWER_PROFILES_SIGNALS[DBUS__POWER_PROFILES_PROFILE_RELEASED], 0, arg_cookie);
}

/**
 * dbus_power_profiles_call_hold_profile:
 * @proxy: A #DbusPowerProfilesProxy.
 * @arg_profile: Argument to pass with the method invocation.
 * @arg_reason: Argument to pass with the method invocation.
 * @arg_application_id: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-net-hadess-PowerProfiles.HoldProfile">HoldProfile()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call dbus_power_profiles_call_hold_profile_finish() to get the result of the operation.
 *
 * See dbus_power_profiles_call_hold_profile_sync() for the synchronous, blocking version of this method.
 */
void
dbus_power_profiles_call_hold_profile (
    DbusPowerProfiles *proxy,
    const gchar *arg_profile,
    const gchar *arg_reason,
    const gchar *arg_application_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "HoldProfile",
    g_variant_new ("(sss)",
                   arg_profile,
                   arg_reason,
                   arg_application_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * dbus_power_profiles_call_hold_profile_finish:
 * @proxy: A #DbusPowerProfilesProxy.
 * @out_cookie: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_power_profiles_call_hold_profile().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with dbus_power_profiles_call_hold_profile().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
dbus_power_profiles_call_hold_profile_finish (
    DbusPowerProfiles *proxy,
    guint *out_cookie,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_cookie);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_power_profiles_call_hold_profile_sync:
 * @proxy: A #DbusPowerProfilesProxy.
 * @arg_profile: Argument to pass with the method invocation.
 * @arg_reason: Argument to pass with the method invocation.
 * @arg_application_id: Argument to pass with the method invocation.
 * @out_cookie: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-net-hadess-PowerProfiles.HoldProfile">HoldProfile()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See dbus_power_profiles_call_hold_profile() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
dbus_power_profiles_call_hold_profile_sync (
    DbusPowerProfiles *proxy,
    const gchar *arg_profile,
    const gchar *arg_reason,
    const gchar *arg_application_id,
    guint *out_cookie,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "HoldProfile",
    g_variant_new ("(sss)",
                   arg_profile,
                   arg_reason,
                   arg_application_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_cookie);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_power_profiles_call_release_profile:
 * @proxy: A #DbusPowerProfilesProxy.
 * @arg_cookie: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-net-hadess-PowerProfiles.ReleaseProfile">ReleaseProfile()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call dbus_power_profiles_call_release_profile_finish() to get the result of the operation.
 *
 * See dbus_power_profiles_call_release_profile_sync() for the synchronous, blocking version of this method.
 */
void
dbus_power_profiles_call_release_profile (
    DbusPowerProfiles *proxy,
    guint arg_cookie,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ReleaseProfile",
    g_variant_new ("(u)",
                   arg_cookie),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * dbus_power_profiles_call_release_profile_finish:
 * @proxy: A #DbusPowerProfilesProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_power_profiles_call_release_profile().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with dbus_power_profiles_call_release_profile().
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
dbus_power_profiles_call_release_profile_finish (
    DbusPowerProfiles *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_power_profiles_call_release_profile_sync:
 * @proxy: A #DbusPowerProfilesProxy.
 * @arg_cookie: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-net-hadess-PowerProfiles.ReleaseProfile">ReleaseProfile()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See dbus_power_profiles_call_release_profile() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeeded, %FALSE if @error is set.
 */
gboolean
dbus_power_profiles_call_release_profile_sync (
    DbusPowerProfiles *proxy,
    guint arg_cookie,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ReleaseProfile",
    g_variant_new ("(u)",
                   arg_cookie),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * dbus_power_profiles_complete_hold_profile:
 * @object: A #DbusPowerProfiles.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @cookie: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-net-hadess-PowerProfiles.HoldProfile">HoldProfile()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
dbus_power_profiles_complete_hold_profile (
    DbusPowerProfiles *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation,
    guint cookie)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(u)",
                   cookie));
}

/**
 * dbus_power_profiles_complete_release_profile:
 * @object: A #DbusPowerProfiles.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-net-hadess-PowerProfiles.ReleaseProfile">ReleaseProfile()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
dbus_power_profiles_complete_release_profile (
    DbusPowerProfiles *object G_GNUC_UNUSED,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * DbusPowerProfilesProxy:
 *
 * The #DbusPowerProfilesProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * DbusPowerProfilesProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #DbusPowerProfilesProxy.
 */

struct _DbusPowerProfilesProxyPrivate
{
  GData *qdata;
};

static void dbus_power_profiles_proxy_iface_init (DbusPowerProfilesIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (DbusPowerProfilesProxy, dbus_power_profiles_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (DbusPowerProfilesProxy)
                         G_IMPLEMENT_INTERFACE (DBUS_TYPE_POWER_PROFILES, dbus_power_profiles_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (DbusPowerProfilesProxy, dbus_power_profiles_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (DBUS_TYPE_POWER_PROFILES, dbus_power_profiles_proxy_iface_init))

#endif
static void
dbus_power_profiles_proxy_finalize (GObject *object)
{
  DbusPowerProfilesProxy *proxy = DBUS_POWER_PROFILES_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (dbus_power_profiles_proxy_parent_class)->finalize (object);
}

static void
dbus_power_profiles_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 6);
  info = (const _ExtendedGDBusPropertyInfo *) _dbus_power_profiles_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
dbus_power_profiles_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface net.hadess.PowerProfiles: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
dbus_power_profiles_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 6);
  info = (const _ExtendedGDBusPropertyInfo *) _dbus_power_profiles_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "net.hadess.PowerProfiles", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) dbus_power_profiles_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
dbus_power_profiles_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_dbus_power_profiles_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], DBUS_TYPE_POWER_PROFILES);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, DBUS_TYPE_POWER_PROFILES);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
dbus_power_profiles_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  DbusPowerProfilesProxy *proxy = DBUS_POWER_PROFILES_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dbus_power_profiles_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dbus_power_profiles_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static const gchar *
dbus_power_profiles_proxy_get_active_profile (DbusPowerProfiles *object)
{
  DbusPowerProfilesProxy *proxy = DBUS_POWER_PROFILES_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "ActiveProfile");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
dbus_power_profiles_proxy_get_performance_inhibited (DbusPowerProfiles *object)
{
  DbusPowerProfilesProxy *proxy = DBUS_POWER_PROFILES_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "PerformanceInhibited");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static const gchar *
dbus_power_profiles_proxy_get_performance_degraded (DbusPowerProfiles *object)
{
  DbusPowerProfilesProxy *proxy = DBUS_POWER_PROFILES_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "PerformanceDegraded");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static GVariant *
dbus_power_profiles_proxy_get_profiles (DbusPowerProfiles *object)
{
  DbusPowerProfilesProxy *proxy = DBUS_POWER_PROFILES_PROXY (object);
  GVariant *variant;
  GVariant *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Profiles");
  value = variant;
  if (variant != NULL)
    g_variant_unref (variant);
  return value;
}

static const gchar *const *
dbus_power_profiles_proxy_get_actions (DbusPowerProfiles *object)
{
  DbusPowerProfilesProxy *proxy = DBUS_POWER_PROFILES_PROXY (object);
  GVariant *variant;
  const gchar *const *value = NULL;
  value = g_datalist_get_data (&proxy->priv->qdata, "Actions");
  if (value != NULL)
    return value;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Actions");
  if (variant != NULL)
    {
      value = g_variant_get_strv (variant, NULL);
      g_datalist_set_data_full (&proxy->priv->qdata, "Actions", (gpointer) value, g_free);
      g_variant_unref (variant);
    }
  return value;
}

static GVariant *
dbus_power_profiles_proxy_get_active_profile_holds (DbusPowerProfiles *object)
{
  DbusPowerProfilesProxy *proxy = DBUS_POWER_PROFILES_PROXY (object);
  GVariant *variant;
  GVariant *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "ActiveProfileHolds");
  value = variant;
  if (variant != NULL)
    g_variant_unref (variant);
  return value;
}

static void
dbus_power_profiles_proxy_init (DbusPowerProfilesProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = dbus_power_profiles_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, DBUS_TYPE_POWER_PROFILES_PROXY, DbusPowerProfilesProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), dbus_power_profiles_interface_info ());
}

static void
dbus_power_profiles_proxy_class_init (DbusPowerProfilesProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = dbus_power_profiles_proxy_finalize;
  gobject_class->get_property = dbus_power_profiles_proxy_get_property;
  gobject_class->set_property = dbus_power_profiles_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = dbus_power_profiles_proxy_g_signal;
  proxy_class->g_properties_changed = dbus_power_profiles_proxy_g_properties_changed;

  dbus_power_profiles_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (DbusPowerProfilesProxyPrivate));
#endif
}

static void
dbus_power_profiles_proxy_iface_init (DbusPowerProfilesIface *iface)
{
  iface->get_active_profile = dbus_power_profiles_proxy_get_active_profile;
  iface->get_performance_inhibited = dbus_power_profiles_proxy_get_performance_inhibited;
  iface->get_performance_degraded = dbus_power_profiles_proxy_get_performance_degraded;
  iface->get_profiles = dbus_power_profiles_proxy_get_profiles;
  iface->get_actions = dbus_power_profiles_proxy_get_actions;
  iface->get_active_profile_holds = dbus_power_profiles_proxy_get_active_profile_holds;
}

/**
 * dbus_power_profiles_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-net-hadess-PowerProfiles.top_of_page">net.hadess.PowerProfiles</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call dbus_power_profiles_proxy_new_finish() to get the result of the operation.
 *
 * See dbus_power_profiles_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
dbus_power_profiles_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (DBUS_TYPE_POWER_PROFILES_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "net.hadess.PowerProfiles", NULL);
}

/**
 * dbus_power_profiles_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_power_profiles_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with dbus_power_profiles_proxy_new().
 *
 * Returns: (transfer full) (type DbusPowerProfilesProxy): The constructed proxy object or %NULL if @error is set.
 */
DbusPowerProfiles *
dbus_power_profiles_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return DBUS_POWER_PROFILES (ret);
  else
    return NULL;
}

/**
 * dbus_power_profiles_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-net-hadess-PowerProfiles.top_of_page">net.hadess.PowerProfiles</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See dbus_power_profiles_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type DbusPowerProfilesProxy): The constructed proxy object or %NULL if @error is set.
 */
DbusPowerProfiles *
dbus_power_profiles_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (DBUS_TYPE_POWER_PROFILES_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "net.hadess.PowerProfiles", NULL);
  if (ret != NULL)
    return DBUS_POWER_PROFILES (ret);
  else
    return NULL;
}


/**
 * dbus_power_profiles_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like dbus_power_profiles_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call dbus_power_profiles_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See dbus_power_profiles_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
dbus_power_profiles_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (DBUS_TYPE_POWER_PROFILES_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "net.hadess.PowerProfiles", NULL);
}

/**
 * dbus_power_profiles_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to dbus_power_profiles_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with dbus_power_profiles_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type DbusPowerProfilesProxy): The constructed proxy object or %NULL if @error is set.
 */
DbusPowerProfiles *
dbus_power_profiles_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return DBUS_POWER_PROFILES (ret);
  else
    return NULL;
}

/**
 * dbus_power_profiles_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like dbus_power_profiles_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See dbus_power_profiles_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type DbusPowerProfilesProxy): The constructed proxy object or %NULL if @error is set.
 */
DbusPowerProfiles *
dbus_power_profiles_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (DBUS_TYPE_POWER_PROFILES_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "net.hadess.PowerProfiles", NULL);
  if (ret != NULL)
    return DBUS_POWER_PROFILES (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * DbusPowerProfilesSkeleton:
 *
 * The #DbusPowerProfilesSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * DbusPowerProfilesSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #DbusPowerProfilesSkeleton.
 */

struct _DbusPowerProfilesSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_dbus_power_profiles_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], DBUS_TYPE_POWER_PROFILES);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, DBUS_TYPE_POWER_PROFILES);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_dbus_power_profiles_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dbus_power_profiles_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_dbus_power_profiles_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_dbus_power_profiles_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _dbus_power_profiles_skeleton_vtable =
{
  _dbus_power_profiles_skeleton_handle_method_call,
  _dbus_power_profiles_skeleton_handle_get_property,
  _dbus_power_profiles_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
dbus_power_profiles_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return dbus_power_profiles_interface_info ();
}

static GDBusInterfaceVTable *
dbus_power_profiles_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_dbus_power_profiles_skeleton_vtable;
}

static GVariant *
dbus_power_profiles_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_dbus_power_profiles_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _dbus_power_profiles_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _dbus_power_profiles_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _dbus_power_profiles_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "net.hadess.PowerProfiles", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _dbus_power_profiles_emit_changed (gpointer user_data);

static void
dbus_power_profiles_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _dbus_power_profiles_emit_changed (skeleton);
}

static void
_dbus_power_profiles_on_signal_profile_released (
    DbusPowerProfiles *object,
    guint arg_cookie)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(u)",
                   arg_cookie));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "net.hadess.PowerProfiles", "ProfileReleased",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void dbus_power_profiles_skeleton_iface_init (DbusPowerProfilesIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (DbusPowerProfilesSkeleton, dbus_power_profiles_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (DbusPowerProfilesSkeleton)
                         G_IMPLEMENT_INTERFACE (DBUS_TYPE_POWER_PROFILES, dbus_power_profiles_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (DbusPowerProfilesSkeleton, dbus_power_profiles_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (DBUS_TYPE_POWER_PROFILES, dbus_power_profiles_skeleton_iface_init))

#endif
static void
dbus_power_profiles_skeleton_finalize (GObject *object)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (object);
  guint n;
  for (n = 0; n < 6; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (dbus_power_profiles_skeleton_parent_class)->finalize (object);
}

static void
dbus_power_profiles_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 6);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_dbus_power_profiles_emit_changed (gpointer user_data)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "net.hadess.PowerProfiles",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_dbus_power_profiles_schedule_emit_changed (DbusPowerProfilesSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
dbus_power_profiles_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _dbus_power_profiles_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _dbus_power_profiles_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
dbus_power_profiles_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 6);
  info = (const _ExtendedGDBusPropertyInfo *) _dbus_power_profiles_property_info_pointers[prop_id - 1];
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL &&
          info->emits_changed_signal)
        _dbus_power_profiles_schedule_emit_changed (skeleton, info, prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
dbus_power_profiles_skeleton_init (DbusPowerProfilesSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = dbus_power_profiles_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, DBUS_TYPE_POWER_PROFILES_SKELETON, DbusPowerProfilesSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 6);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[2], G_TYPE_STRING);
  g_value_init (&skeleton->priv->properties[3], G_TYPE_VARIANT);
  g_value_init (&skeleton->priv->properties[4], G_TYPE_STRV);
  g_value_init (&skeleton->priv->properties[5], G_TYPE_VARIANT);
}

static const gchar *
dbus_power_profiles_skeleton_get_active_profile (DbusPowerProfiles *object)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_marshal_value_peek_string (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
dbus_power_profiles_skeleton_get_performance_inhibited (DbusPowerProfiles *object)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_marshal_value_peek_string (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *
dbus_power_profiles_skeleton_get_performance_degraded (DbusPowerProfiles *object)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_marshal_value_peek_string (&(skeleton->priv->properties[2]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static GVariant *
dbus_power_profiles_skeleton_get_profiles (DbusPowerProfiles *object)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (object);
  GVariant *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_marshal_value_peek_variant (&(skeleton->priv->properties[3]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static const gchar *const *
dbus_power_profiles_skeleton_get_actions (DbusPowerProfiles *object)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (object);
  const gchar *const *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_marshal_value_peek_boxed (&(skeleton->priv->properties[4]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static GVariant *
dbus_power_profiles_skeleton_get_active_profile_holds (DbusPowerProfiles *object)
{
  DbusPowerProfilesSkeleton *skeleton = DBUS_POWER_PROFILES_SKELETON (object);
  GVariant *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_marshal_value_peek_variant (&(skeleton->priv->properties[5]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
dbus_power_profiles_skeleton_class_init (DbusPowerProfilesSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = dbus_power_profiles_skeleton_finalize;
  gobject_class->get_property = dbus_power_profiles_skeleton_get_property;
  gobject_class->set_property = dbus_power_profiles_skeleton_set_property;
  gobject_class->notify       = dbus_power_profiles_skeleton_notify;


  dbus_power_profiles_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = dbus_power_profiles_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = dbus_power_profiles_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = dbus_power_profiles_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = dbus_power_profiles_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (DbusPowerProfilesSkeletonPrivate));
#endif
}

static void
dbus_power_profiles_skeleton_iface_init (DbusPowerProfilesIface *iface)
{
  iface->profile_released = _dbus_power_profiles_on_signal_profile_released;
  iface->get_active_profile = dbus_power_profiles_skeleton_get_active_profile;
  iface->get_performance_inhibited = dbus_power_profiles_skeleton_get_performance_inhibited;
  iface->get_performance_degraded = dbus_power_profiles_skeleton_get_performance_degraded;
  iface->get_profiles = dbus_power_profiles_skeleton_get_profiles;
  iface->get_actions = dbus_power_profiles_skeleton_get_actions;
  iface->get_active_profile_holds = dbus_power_profiles_skeleton_get_active_profile_holds;
}

/**
 * dbus_power_profiles_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-net-hadess-PowerProfiles.top_of_page">net.hadess.PowerProfiles</link>.
 *
 * Returns: (transfer full) (type DbusPowerProfilesSkeleton): The skeleton object.
 */
DbusPowerProfiles *
dbus_power_profiles_skeleton_new (void)
{
  return DBUS_POWER_PROFILES (g_object_new (DBUS_TYPE_POWER_PROFILES_SKELETON, NULL));
}

